"""Routes for the qr-generator and barcode-generator tools."""

import logging

from fastapi import APIRouter, File, Form, Response, UploadFile

from app.modules.devtools.dev_tools_controller import dev_tools_controller

logger = logging.getLogger(__name__)

image_gen_router = APIRouter(tags=["Developer Tools"])

_EXTENSION_BY_TYPE = {
    "image/png": "png",
    "image/webp": "webp",
    "image/svg+xml": "svg",
}


def _attachment(data: bytes, content_type: str, stem: str) -> Response:
    """Return generated bytes with a filename the browser can save.

    Without ``Content-Disposition`` the page's download fell back to a
    file literally called ``download`` with no extension.
    """
    extension = _EXTENSION_BY_TYPE.get(content_type, "bin")
    return Response(
        content=data,
        media_type=content_type,
        headers={
            "Content-Disposition": (
                f'attachment; filename="{stem}.{extension}"'
            )
        },
    )


@image_gen_router.post("/qr")
async def generate_qr(
    content: str = Form(...),
    box_size: int = Form(10),
    border: int = Form(4),
    fill_color: str = Form("#163300"),
    back_color: str = Form("#ffffff"),
    output_format: str = Form("png"),
    logo: UploadFile | None = File(None),
):
    logger.info(
        "generate_qr: content_len=%d format=%s has_logo=%s",
        len(content), output_format, bool(logo),
    )
    data, content_type = await dev_tools_controller.qr(
        content,
        box_size=box_size,
        border=border,
        fill_color=fill_color,
        back_color=back_color,
        output_format=output_format,
        logo=logo,
    )
    return _attachment(data, content_type, "qr-code")


@image_gen_router.post("/barcode")
async def generate_barcode(
    content: str = Form(...),
    code_type: str = Form("code128"),
    output_format: str = Form("png"),
):
    logger.info(
        "generate_barcode: content_len=%d type=%s format=%s",
        len(content), code_type, output_format,
    )
    data, content_type = await dev_tools_controller.barcode(
        content,
        code_type=code_type,
        output_format=output_format,
    )
    return _attachment(data, content_type, f"barcode-{code_type}")
